spring:
  datasource:
    url: jdbc:mysql://localhost:3306/rooting_main?serverTimezone=Asia/Seoul
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: jkimpro10
    password: jun48675@#
    jpa:
      hibernate:
        ddl-auto: update # 운영시에는 validate 추천
      show-sql: true
#  kafka:
#    bootstrap-servers: localhost:9092
#bootstrap-servers: 10.52.220.194:9092,10.52.220.195:9092,10.52.220.196:9092

  kafka:
    bootstrap-servers:
  #    - 10.52.220.194:9092
  #    - 10.52.220.195:9092
  #    - 10.52.220.196:9092
        - localhost:9092
    enable:
      auto:
        commit: false
    ackmode: MANUAL
    offset:
      reset: lastest